### ISSUE TITLE
Missing id_token_hint on logout

### ISSUE THREAD

**Issue by bjornharrtell** [adfinis-sygroup/ember-simple-auth-oidc#180]
At this point:
https://github.com/adfinis-sygroup/ember-simple-auth-oidc/blob/13c33a0873c2a1ea32388bec9a26b1f524406456/addon/mixins/oidc-application-route-mixin.js#L48

Session is already cleared so id_token will be undefined.

**Comment by lele-melis** [comment]
+1 
I am stuck on the very same issue.

**Comment by bjornharrtell** [comment]
@anehx any chance of getting this merged and released in a near future?
